#pragma once

#include <algorithm>
#include <iterator>
#include <list>
#include <map>
#include <memory>
#include <regex>
#include <tuple>
#include <type_traits>
#include <vector>

#include "qaction.h"
#include "qapplication.h"
#include "qboxlayout.h"
#include "qcheckbox.h"
#include "qcombobox.h"
#include "qdebug.h"
#include "qdesktopwidget.h"
#include "qdir.h"
#include "qdockwidget.h"
#include "qevent.h"
#include "qfile.h"
#include "qfiledialog.h"
#include "qformlayout.h"
#include "qgridlayout.h"
#include "qheaderview.h"
#include "qlabel.h"
#include "qlineedit.h"
#include "qlistwidget.h"
#include "qmainwindow.h"
#include "qmenu.h"
#include "qmenubar.h"
#include "qmessagebox.h"
#include "qpainter.h"
#include "qpointer.h"
#include "qproxystyle.h"
#include "qpushbutton.h"
#include "qscrollarea.h"
#include "qscrollbar.h"
#include "qstyleditemdelegate.h"
#include "qstyleoption.h"
#include "qtablewidget.h"
#include "qtabwidget.h"
#include "qtextbrowser.h"
#include "qtextedit.h"
#include "qtimer.h"
#include "qwidget.h"
